name: 📚 Documentation
description: Report an issue related to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Type of documentation issue
      options:
        - Missing documentation
        - Unclear documentation
        - Incorrect documentation
        - Outdated documentation
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation location
      description: Where is the documentation you're referring to?
      placeholder: e.g., README.md, API docs, etc.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe what needs to be added or changed.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested changes
      description: If you have specific suggestions for how to improve the documentation, please share them here.
      placeholder: Your suggested changes or additions...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
